
TG_CAT_COOKING = "Cooking";

TG_DB_COOKING = {
  
  { tag = 162515, name = "Midnight Salmon", cat = TG_CAT_COOKING, skill = 1},
  { tag = 152543, name = "Sand Shifter", cat = TG_CAT_COOKING, skill = 1},
  { tag = 152544, name = "Slimy Mackerel", cat = TG_CAT_COOKING, skill = 1},
  { tag = 152545, name = "Frenzied Fangtooth", cat = TG_CAT_COOKING, skill = 1},
  { tag = 152546, name = "Lane Snapper", cat = TG_CAT_COOKING, skill = 1},
  { tag = 152547, name = "Great Sea Catfish", cat = TG_CAT_COOKING, skill = 1},
  { tag = 152548, name = "Tiragarde Perch", cat = TG_CAT_COOKING, skill = 1},
  { tag = 152549, name = "Redtail Loach", cat = TG_CAT_COOKING, skill = 1},
  { tag = 152631, name = "Briny Flesh", cat = TG_CAT_COOKING, skill = 1},
  { tag = 154897, name = "Stringy Loins", cat = TG_CAT_COOKING, skill = 1},
  { tag = 154898, name = "Meaty Haunch", cat = TG_CAT_COOKING, skill = 1},
  { tag = 154899, name = "Thick Paleo Steak", cat = TG_CAT_COOKING, skill = 1},
  { tag = 160398, name = "Choral Honey", cat = TG_CAT_COOKING, skill = 1},
  { tag = 160399, name = "Wild Flour", cat = TG_CAT_COOKING, skill = 1},
  { tag = 160400, name = "Foosaka", cat = TG_CAT_COOKING, skill = 1},
  { tag = 160709, name = "Fresh Potato", cat = TG_CAT_COOKING, skill = 1},
  { tag = 160710, name = "Wild Berries", cat = TG_CAT_COOKING, skill = 1},
  { tag = 160711, name = "Aromatic Fish Oil", cat = TG_CAT_COOKING, skill = 1},
  { tag = 160712, name = "Powdered Sugar", cat = TG_CAT_COOKING, skill = 1},
  { tag = 163782, name = "Cursed Haunch", cat = TG_CAT_COOKING, skill = 1},
  { tag = 162461, name = "Sanguicell", cat = TG_CAT_COOKING, skill = 1},
  { tag = 133680, name = "Slice of Bacon", cat = TG_CAT_COOKING, skill = 1},
  { tag = 124101, name = "Aethril", cat = TG_CAT_COOKING, skill = 1},
  { tag = 124102, name = "Dreamleaf", cat = TG_CAT_COOKING, skill = 1},
  { tag = 124103, name = "Foxflower", cat = TG_CAT_COOKING, skill = 1},
  { tag = 124104, name = "Fjarnskaggl", cat = TG_CAT_COOKING, skill = 1},
  { tag = 124105, name = "Starlight Rose", cat = TG_CAT_COOKING, skill = 1},
  { tag = 124107, name = "Cursed Queenfish", cat = TG_CAT_COOKING, skill = 1},
  { tag = 124108, name = "Mossgill Perch", cat = TG_CAT_COOKING, skill = 1},
  { tag = 124109, name = "Highmountain Salmon", cat = TG_CAT_COOKING, skill = 1},
  { tag = 124110, name = "Stormray", cat = TG_CAT_COOKING, skill = 1},
  { tag = 124111, name = "Runescale Koi", cat = TG_CAT_COOKING, skill = 1},
  { tag = 124112, name = "Black Barracuda", cat = TG_CAT_COOKING, skill = 1},
  { tag = 124117, name = "Lean Shank", cat = TG_CAT_COOKING, skill = 1},
  { tag = 124118, name = "Fatty Bearsteak", cat = TG_CAT_COOKING, skill = 1},
  { tag = 124119, name = "Big Gamy Ribs", cat = TG_CAT_COOKING, skill = 1},
  { tag = 124120, name = "Leyblood", cat = TG_CAT_COOKING, skill = 1},
  { tag = 124121, name = "Wildfowl Egg", cat = TG_CAT_COOKING, skill = 1},
  { tag = 128304, name = "Yseralline Seed", cat = TG_CAT_COOKING, skill = 1},
  { tag = 133607, name = "Silver Mackerel", cat = TG_CAT_COOKING, skill = 1},
  { tag = 142336, name = "Falcosaur Egg", cat = TG_CAT_COOKING, skill = 1},
  { tag = 109124, name = "Frostweed", cat = TG_CAT_COOKING, skill = 1},
  { tag = 109125, name = "Fireweed", cat = TG_CAT_COOKING, skill = 1},
  { tag = 109126, name = "Gorgrond Flytrap", cat = TG_CAT_COOKING, skill = 1},
  { tag = 109127, name = "Starflower", cat = TG_CAT_COOKING, skill = 1},
  { tag = 109128, name = "Nagrand Arrowbloom", cat = TG_CAT_COOKING, skill = 1},
  { tag = 109129, name = "Talador Orchid", cat = TG_CAT_COOKING, skill = 1},
  { tag = 109131, name = "Raw Clefthoof Meat", cat = TG_CAT_COOKING, skill = 1},
  { tag = 109132, name = "Raw Talbuk Meat", cat = TG_CAT_COOKING, skill = 1},
  { tag = 109133, name = "Rylak Egg", cat = TG_CAT_COOKING, skill = 1},
  { tag = 109134, name = "Raw Elekk Meat", cat = TG_CAT_COOKING, skill = 1},
  { tag = 109135, name = "Raw Riverbeast Meat", cat = TG_CAT_COOKING, skill = 1},
  { tag = 109136, name = "Raw Boar Meat", cat = TG_CAT_COOKING, skill = 1},
  { tag = 109137, name = "Crescent Saberfish Flesh", cat = TG_CAT_COOKING, skill = 1},
  { tag = 109138, name = "Jawless Skulker Flesh", cat = TG_CAT_COOKING, skill = 1},
  { tag = 109139, name = "Fat Sleeper Flesh", cat = TG_CAT_COOKING, skill = 1},
  { tag = 109140, name = "Blind Lake Sturgeon Flesh", cat = TG_CAT_COOKING, skill = 1},
  { tag = 109141, name = "Fire Ammonite Tentacle", cat = TG_CAT_COOKING, skill = 1},
  { tag = 109142, name = "Sea Scorpion Segment", cat = TG_CAT_COOKING, skill = 1},
  { tag = 109143, name = "Abyssal Gulper Eel Flesh", cat = TG_CAT_COOKING, skill = 1},
  { tag = 109144, name = "Blackwater Whiptail Flesh", cat = TG_CAT_COOKING, skill = 1},
  { tag = 128499, name = "Fel Egg", cat = TG_CAT_COOKING, skill = 1},
  { tag = 128500, name = "Fel Ham", cat = TG_CAT_COOKING, skill = 1},
  { tag = 74856, name = "Jade Lungfish", cat = TG_CAT_COOKING, skill = 1},
  { tag = 74857, name = "Giant Mantis Shrimp", cat = TG_CAT_COOKING, skill = 1},
  { tag = 74859, name = "Emperor Salmon", cat = TG_CAT_COOKING, skill = 1},
  { tag = 74860, name = "Redbelly Mandarin", cat = TG_CAT_COOKING, skill = 1},
  { tag = 74861, name = "Tiger Gourami", cat = TG_CAT_COOKING, skill = 1},
  { tag = 74863, name = "Jewel Danio", cat = TG_CAT_COOKING, skill = 1},
  { tag = 74864, name = "Reef Octopus", cat = TG_CAT_COOKING, skill = 1},
  { tag = 74865, name = "Krasarang Paddlefish", cat = TG_CAT_COOKING, skill = 1},
  { tag = 74866, name = "Golden Carp", cat = TG_CAT_COOKING, skill = 1},
  { tag = 85506, name = "Viseclaw Meat", cat = TG_CAT_COOKING, skill = 1},
  { tag = 102541, name = "Aged Balsamic Vinegar", cat = TG_CAT_COOKING, skill = 1},
  { tag = 102542, name = "Ancient Pandaren Spices", cat = TG_CAT_COOKING, skill = 1},
  { tag = 102543, name = "Aged Mogu'shan Cheese", cat = TG_CAT_COOKING, skill = 1},
  { tag = 74659, name = "Farm Chicken", cat = TG_CAT_COOKING, skill = 1},
  { tag = 74660, name = "Pandaren Peach", cat = TG_CAT_COOKING, skill = 1},
  { tag = 74661, name = "Black Pepper", cat = TG_CAT_COOKING, skill = 1},
  { tag = 74662, name = "Rice Flour", cat = TG_CAT_COOKING, skill = 1},
  { tag = 74832, name = "Barley", cat = TG_CAT_COOKING, skill = 1},
  { tag = 74833, name = "Raw Tiger Steak", cat = TG_CAT_COOKING, skill = 1},
  { tag = 74834, name = "Mushan Ribs", cat = TG_CAT_COOKING, skill = 1},
  { tag = 74837, name = "Raw Turtle Meat", cat = TG_CAT_COOKING, skill = 1},
  { tag = 74838, name = "Raw Crab Meat", cat = TG_CAT_COOKING, skill = 1},
  { tag = 74839, name = "Wildfowl Breast", cat = TG_CAT_COOKING, skill = 1},
  { tag = 74840, name = "Green Cabbage", cat = TG_CAT_COOKING, skill = 1},
  { tag = 74841, name = "Juicycrunch Carrot", cat = TG_CAT_COOKING, skill = 1},
  { tag = 74842, name = "Mogu Pumpkin", cat = TG_CAT_COOKING, skill = 1},
  { tag = 74843, name = "Scallions", cat = TG_CAT_COOKING, skill = 1},
  { tag = 74844, name = "Red Blossom Leek", cat = TG_CAT_COOKING, skill = 1},
  { tag = 74845, name = "Ginseng", cat = TG_CAT_COOKING, skill = 1},
  { tag = 74846, name = "Witchberries", cat = TG_CAT_COOKING, skill = 1},
  { tag = 74847, name = "Jade Squash", cat = TG_CAT_COOKING, skill = 1},
  { tag = 74848, name = "Striped Melon", cat = TG_CAT_COOKING, skill = 1},
  { tag = 74849, name = "Pink Turnip", cat = TG_CAT_COOKING, skill = 1},
  { tag = 74850, name = "White Turnip", cat = TG_CAT_COOKING, skill = 1},
  { tag = 74851, name = "Rice", cat = TG_CAT_COOKING, skill = 1},
  { tag = 74852, name = "Yak Milk", cat = TG_CAT_COOKING, skill = 1},
  { tag = 74853, name = "100 Year Soy Sauce", cat = TG_CAT_COOKING, skill = 1},
  { tag = 74854, name = "Instant Noodles", cat = TG_CAT_COOKING, skill = 1},
  { tag = 75014, name = "Raw Crocolisk Belly", cat = TG_CAT_COOKING, skill = 1},
  { tag = 79246, name = "Delicate Blossom Petals", cat = TG_CAT_COOKING, skill = 1},
  { tag = 79250, name = "Fresh Pomfruit", cat = TG_CAT_COOKING, skill = 1},
  { tag = 85583, name = "Needle Mushrooms", cat = TG_CAT_COOKING, skill = 1},
  { tag = 85584, name = "Silkworm Pupa", cat = TG_CAT_COOKING, skill = 1},
  { tag = 85585, name = "Red Beans", cat = TG_CAT_COOKING, skill = 1},
  { tag = 102536, name = "Fresh Lushroom", cat = TG_CAT_COOKING, skill = 1},
  { tag = 102537, name = "Fresh Silkfeather Hawk Eggs", cat = TG_CAT_COOKING, skill = 1},
  { tag = 102538, name = "Fresh Shao-Tien Rice", cat = TG_CAT_COOKING, skill = 1},
  { tag = 102539, name = "Fresh Strawberries", cat = TG_CAT_COOKING, skill = 1},
  { tag = 102540, name = "Fresh Mangos", cat = TG_CAT_COOKING, skill = 1},
  { tag = 53062, name = "Sharptooth", cat = TG_CAT_COOKING, skill = 1},
  { tag = 53063, name = "Mountain Trout", cat = TG_CAT_COOKING, skill = 1},
  { tag = 53064, name = "Highland Guppy", cat = TG_CAT_COOKING, skill = 1},
  { tag = 53066, name = "Blackbelly Mudfish", cat = TG_CAT_COOKING, skill = 1},
  { tag = 53067, name = "Striped Lurker", cat = TG_CAT_COOKING, skill = 1},
  { tag = 53068, name = "Lavascale Catfish", cat = TG_CAT_COOKING, skill = 1},
  { tag = 53069, name = "Murglesnout", cat = TG_CAT_COOKING, skill = 1},
  { tag = 53070, name = "Fathom Eel", cat = TG_CAT_COOKING, skill = 1},
  { tag = 53071, name = "Algaefin Rockfish", cat = TG_CAT_COOKING, skill = 1},
  { tag = 53072, name = "Deepsea Sagefish", cat = TG_CAT_COOKING, skill = 1},
  { tag = 62778, name = "Toughened Flesh", cat = TG_CAT_COOKING, skill = 1},
  { tag = 62779, name = "Monstrous Claw", cat = TG_CAT_COOKING, skill = 1},
  { tag = 62780, name = "Snake Eye", cat = TG_CAT_COOKING, skill = 1},
  { tag = 62781, name = "Giant Turtle Tongue", cat = TG_CAT_COOKING, skill = 1},
  { tag = 62782, name = "Dragon Flank", cat = TG_CAT_COOKING, skill = 1},
  { tag = 62783, name = "Basilisk \"Liver\"", cat = TG_CAT_COOKING, skill = 1},
  { tag = 62784, name = "Crocolisk Tail", cat = TG_CAT_COOKING, skill = 1},
  { tag = 62785, name = "Delicate Wing", cat = TG_CAT_COOKING, skill = 1},
  { tag = 62786, name = "Cocoa Beans", cat = TG_CAT_COOKING, skill = 1},
  { tag = 62791, name = "Blood Shrimp", cat = TG_CAT_COOKING, skill = 1},
  { tag = 43007, name = "Northern Spices", cat = TG_CAT_COOKING, skill = 1},
  { tag = 36782, name = "Succulent Clam Meat", cat = TG_CAT_COOKING, skill = 1},
  { tag = 34736, name = "Chunk o' Mammoth", cat = TG_CAT_COOKING, skill = 1},
  { tag = 41800, name = "Deep Sea Monsterbelly", cat = TG_CAT_COOKING, skill = 1},
  { tag = 41801, name = "Moonglow Cuttlefish", cat = TG_CAT_COOKING, skill = 1},
  { tag = 41802, name = "Imperial Manta Ray", cat = TG_CAT_COOKING, skill = 1},
  { tag = 41803, name = "Rockfin Grouper", cat = TG_CAT_COOKING, skill = 1},
  { tag = 41805, name = "Borean Man O' War", cat = TG_CAT_COOKING, skill = 1},
  { tag = 41806, name = "Musselback Sculpin", cat = TG_CAT_COOKING, skill = 1},
  { tag = 41807, name = "Dragonfin Angelfish", cat = TG_CAT_COOKING, skill = 1},
  { tag = 41808, name = "Bonescale Snapper", cat = TG_CAT_COOKING, skill = 1},
  { tag = 41809, name = "Glacial Salmon", cat = TG_CAT_COOKING, skill = 1},
  { tag = 41810, name = "Fangtooth Herring", cat = TG_CAT_COOKING, skill = 1},
  { tag = 41812, name = "Barrelhead Goby", cat = TG_CAT_COOKING, skill = 1},
  { tag = 41813, name = "Nettlefish", cat = TG_CAT_COOKING, skill = 1},
  { tag = 43009, name = "Shoveltusk Flank", cat = TG_CAT_COOKING, skill = 1},
  { tag = 43010, name = "Worm Meat", cat = TG_CAT_COOKING, skill = 1},
  { tag = 43011, name = "Worg Haunch", cat = TG_CAT_COOKING, skill = 1},
  { tag = 43012, name = "Rhino Meat", cat = TG_CAT_COOKING, skill = 1},
  { tag = 43013, name = "Chilled Meat", cat = TG_CAT_COOKING, skill = 1},
  { tag = 43501, name = "Northern Egg", cat = TG_CAT_COOKING, skill = 1},
  { tag = 22577, name = "Mote of Shadow", cat = TG_CAT_COOKING, skill = 1},
  { tag = 24477, name = "Jaggal Clam Meat", cat = TG_CAT_COOKING, skill = 1},
  { tag = 33823, name = "Bloodfin Catfish", cat = TG_CAT_COOKING, skill = 1},
  { tag = 33824, name = "Crescent-Tail Skullfish", cat = TG_CAT_COOKING, skill = 1},
  { tag = 21024, name = "Chimaerok Tenderloin", cat = TG_CAT_COOKING, skill = 1},
  { tag = 27422, name = "Barbed Gill Trout", cat = TG_CAT_COOKING, skill = 1},
  { tag = 27425, name = "Spotted Feltail", cat = TG_CAT_COOKING, skill = 1},
  { tag = 27429, name = "Zangarian Sporefish", cat = TG_CAT_COOKING, skill = 1},
  { tag = 27435, name = "Figluster's Mudfish", cat = TG_CAT_COOKING, skill = 1},
  { tag = 27437, name = "Icefin Bluefish", cat = TG_CAT_COOKING, skill = 1},
  { tag = 27438, name = "Golden Darter", cat = TG_CAT_COOKING, skill = 1},
  { tag = 27439, name = "Furious Crawdad", cat = TG_CAT_COOKING, skill = 1},
  { tag = 27515, name = "Huge Spotted Feltail", cat = TG_CAT_COOKING, skill = 1},
  { tag = 27516, name = "Enormous Barbed Gill Trout", cat = TG_CAT_COOKING, skill = 1},
  { tag = 27671, name = "Buzzard Meat", cat = TG_CAT_COOKING, skill = 1},
  { tag = 27674, name = "Ravager Flesh", cat = TG_CAT_COOKING, skill = 1},
  { tag = 27677, name = "Chunk o' Basilisk", cat = TG_CAT_COOKING, skill = 1},
  { tag = 27678, name = "Clefthoof Meat", cat = TG_CAT_COOKING, skill = 1},
  { tag = 27681, name = "Warped Flesh", cat = TG_CAT_COOKING, skill = 1},
  { tag = 27682, name = "Talbuk Venison", cat = TG_CAT_COOKING, skill = 1},
  { tag = 31670, name = "Raptor Ribs", cat = TG_CAT_COOKING, skill = 1},
  { tag = 31671, name = "Serpent Flesh", cat = TG_CAT_COOKING, skill = 1},
  { tag = 12808, name = "Essence of Undeath", cat = TG_CAT_COOKING, skill = 1},
  { tag = 13888, name = "Darkclaw Lobster", cat = TG_CAT_COOKING, skill = 1},
  { tag = 13889, name = "Raw Whitescale Salmon", cat = TG_CAT_COOKING, skill = 1},
  { tag = 20424, name = "Sandworm Meat", cat = TG_CAT_COOKING, skill = 1},
  { tag = 35562, name = "Bear Flank", cat = TG_CAT_COOKING, skill = 1},
  { tag = 4603, name = "Raw Spotted Yellowtail", cat = TG_CAT_COOKING, skill = 1},
  { tag = 7974, name = "Zesty Clam Meat", cat = TG_CAT_COOKING, skill = 1},
  { tag = 12207, name = "Giant Egg", cat = TG_CAT_COOKING, skill = 1},
  { tag = 13754, name = "Raw Glossy Mightfish", cat = TG_CAT_COOKING, skill = 1},
  { tag = 13756, name = "Raw Summer Bass", cat = TG_CAT_COOKING, skill = 1},
  { tag = 13757, name = "Lightning Eel", cat = TG_CAT_COOKING, skill = 1},
  { tag = 13758, name = "Raw Redgill", cat = TG_CAT_COOKING, skill = 1},
  { tag = 13759, name = "Raw Nightfin Snapper", cat = TG_CAT_COOKING, skill = 1},
  { tag = 13760, name = "Raw Sunscale Salmon", cat = TG_CAT_COOKING, skill = 1},
  { tag = 9061, name = "Goblin Rocket Fuel", cat = TG_CAT_COOKING, skill = 1},
  { tag = 8150, name = "Deeprock Salt", cat = TG_CAT_COOKING, skill = 1},
  { tag = 12205, name = "White Spider Meat", cat = TG_CAT_COOKING, skill = 1},
  { tag = 12206, name = "Tender Crab Meat", cat = TG_CAT_COOKING, skill = 1},
  { tag = 12208, name = "Tender Wolf Meat", cat = TG_CAT_COOKING, skill = 1},
  { tag = 21153, name = "Raw Greater Sagefish", cat = TG_CAT_COOKING, skill = 1},
  { tag = 3404, name = "Buzzard Wing", cat = TG_CAT_COOKING, skill = 1},
  { tag = 4655, name = "Giant Clam Meat", cat = TG_CAT_COOKING, skill = 1},
  { tag = 6362, name = "Raw Rockscale Cod", cat = TG_CAT_COOKING, skill = 1},
  { tag = 8365, name = "Raw Mithril Head Trout", cat = TG_CAT_COOKING, skill = 1},
  { tag = 12204, name = "Heavy Kodo Meat", cat = TG_CAT_COOKING, skill = 1},
  { tag = 3821, name = "Goldthorn", cat = TG_CAT_COOKING, skill = 1},
  { tag = 3712, name = "Turtle Meat", cat = TG_CAT_COOKING, skill = 1},
  { tag = 12037, name = "Mystery Meat", cat = TG_CAT_COOKING, skill = 1},
  { tag = 12184, name = "Raptor Flesh", cat = TG_CAT_COOKING, skill = 1},
  { tag = 12202, name = "Tiger Meat", cat = TG_CAT_COOKING, skill = 1},
  { tag = 12203, name = "Red Wolf Meat", cat = TG_CAT_COOKING, skill = 1},
  { tag = 2251, name = "Gooey Spider Leg", cat = TG_CAT_COOKING, skill = 1},
  { tag = 4402, name = "Small Flame Sac", cat = TG_CAT_COOKING, skill = 1},
  { tag = 6308, name = "Raw Bristle Whisker Catfish", cat = TG_CAT_COOKING, skill = 1},
  { tag = 3667, name = "Tender Crocolisk Meat", cat = TG_CAT_COOKING, skill = 1},
  { tag = 3731, name = "Lion Meat", cat = TG_CAT_COOKING, skill = 1},
  { tag = 5471, name = "Stag Meat", cat = TG_CAT_COOKING, skill = 1},
  { tag = 5504, name = "Tangy Clam Meat", cat = TG_CAT_COOKING, skill = 1},
  { tag = 3685, name = "Raptor Egg", cat = TG_CAT_COOKING, skill = 1},
  { tag = 5470, name = "Thunder Lizard Tail", cat = TG_CAT_COOKING, skill = 1},
  { tag = 3730, name = "Big Bear Meat", cat = TG_CAT_COOKING, skill = 1},
  { tag = 21071, name = "Raw Sagefish", cat = TG_CAT_COOKING, skill = 1},
  { tag = 1015, name = "Lean Wolf Flank", cat = TG_CAT_COOKING, skill = 1},
  { tag = 1468, name = "Murloc Fin", cat = TG_CAT_COOKING, skill = 1},
  { tag = 1080, name = "Tough Condor Meat", cat = TG_CAT_COOKING, skill = 1},
  { tag = 2452, name = "Swiftthistle", cat = TG_CAT_COOKING, skill = 1},
  { tag = 5468, name = "Soft Frenzy Flesh", cat = TG_CAT_COOKING, skill = 1},
  { tag = 6289, name = "Raw Longjaw Mud Snapper", cat = TG_CAT_COOKING, skill = 1},
  { tag = 6317, name = "Raw Loch Frenzy", cat = TG_CAT_COOKING, skill = 1},
  { tag = 6361, name = "Raw Rainbow Fin Albacore", cat = TG_CAT_COOKING, skill = 1},
  { tag = 22644, name = "Crunchy Spider Leg", cat = TG_CAT_COOKING, skill = 1},
  { tag = 2677, name = "Boar Ribs", cat = TG_CAT_COOKING, skill = 1},
  { tag = 2924, name = "Crocolisk Meat", cat = TG_CAT_COOKING, skill = 1},
  { tag = 5503, name = "Clam Meat", cat = TG_CAT_COOKING, skill = 1},
  { tag = 2674, name = "Crawler Meat", cat = TG_CAT_COOKING, skill = 1},
  { tag = 2675, name = "Crawler Claw", cat = TG_CAT_COOKING, skill = 1},
  { tag = 723, name = "Goretusk Liver", cat = TG_CAT_COOKING, skill = 1},
  { tag = 3173, name = "Bear Meat", cat = TG_CAT_COOKING, skill = 1},
  { tag = 67229, name = "Stag Flank", cat = TG_CAT_COOKING, skill = 1},
  { tag = 785, name = "Mageroyal", cat = TG_CAT_COOKING, skill = 1},
  { tag = 2673, name = "Coyote Meat", cat = TG_CAT_COOKING, skill = 1},
  { tag = 5467, name = "Kodo Meat", cat = TG_CAT_COOKING, skill = 1},
  { tag = 5469, name = "Strider Meat", cat = TG_CAT_COOKING, skill = 1},
  { tag = 5466, name = "Scorpid Stinger", cat = TG_CAT_COOKING, skill = 1},
  { tag = 769, name = "Chunk of Boar Meat", cat = TG_CAT_COOKING, skill = 1},
  { tag = 2672, name = "Stringy Wolf Meat", cat = TG_CAT_COOKING, skill = 1},
  { tag = 2678, name = "Mild Spices", cat = TG_CAT_COOKING, skill = 1},
  { tag = 2886, name = "Crag Boar Rib", cat = TG_CAT_COOKING, skill = 1},
  { tag = 5465, name = "Small Spider Leg", cat = TG_CAT_COOKING, skill = 1},
  { tag = 6291, name = "Raw Brilliant Smallfish", cat = TG_CAT_COOKING, skill = 1},
  { tag = 6303, name = "Raw Slitherskin Mackerel", cat = TG_CAT_COOKING, skill = 1},
  { tag = 6889, name = "Small Egg", cat = TG_CAT_COOKING, skill = 1},
  { tag = 12223, name = "Meaty Bat Wing", cat = TG_CAT_COOKING, skill = 1},
  { tag = 17194, name = "Holiday Spices", cat = TG_CAT_COOKING, skill = 1},
  { tag = 27668, name = "Lynx Meat", cat = TG_CAT_COOKING, skill = 1},
  { tag = 27669, name = "Bat Flesh", cat = TG_CAT_COOKING, skill = 1},
  { tag = 30817, name = "Simple Flour", cat = TG_CAT_COOKING, skill = 1},
  { tag = 44835, name = "Autumnal Herbs", cat = TG_CAT_COOKING, skill = 1},
  { tag = 5051, name = "Dig Rat", cat = TG_CAT_COOKING, skill = 1},
  { tag = 23676, name = "Moongraze Stag Tenderloin", cat = TG_CAT_COOKING, skill = 1},
  { tag = 44834, name = "Wild Turkey", cat = TG_CAT_COOKING, skill = 1},
  { tag = 44853, name = "Honey", cat = TG_CAT_COOKING, skill = 1},
  { tag = 124669, name = "Darkmoon Daggermaw", cat = TG_CAT_COOKING, skill = 1},
  { tag = 129100, name = "Gem Chip", cat = TG_CAT_COOKING, skill = 1},
  { tag = 133588, name = "Flaked Sea Salt", cat = TG_CAT_COOKING, skill = 1},
  { tag = 133589, name = "Dalapeño Pepper", cat = TG_CAT_COOKING, skill = 1},
  { tag = 133590, name = "Muskenbutter", cat = TG_CAT_COOKING, skill = 1},
  { tag = 133591, name = "River Onion", cat = TG_CAT_COOKING, skill = 1},
  { tag = 133592, name = "Stonedark Snail", cat = TG_CAT_COOKING, skill = 1},
  { tag = 133593, name = "Royal Olive", cat = TG_CAT_COOKING, skill = 1},
  { tag = 160705, name = "Major's Frothy Coffee", cat = TG_CAT_COOKING, skill = 1}

}

TGC_PLUGIN_CATEGORIES = {
    { db = TG_DB_COOKING, name = TG_CAT_COOKING,  smenu = TG_PREFIX_SHOW..TG_CAT_COOKING, profession = "Cooking", cat = TG_CAT_COOKING, skill = 1},
}

TGC_MINABLES = {}